// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQ_8IEKMv0yHALdWw6k8I5eyamyr5JfEY',
    appId: '1:981749862755:web:3c00593dbc57c4270ec356',
    messagingSenderId: '981749862755',
    projectId: 'skilloom',
    authDomain: 'skilloom.firebaseapp.com',
    storageBucket: 'skilloom.appspot.com',
    measurementId: 'G-CSKWQERDN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwJBJl9BTH-sqQfkYXTwvKbkzx-OOc-uw',
    appId: '1:981749862755:android:4c848d88581a1bac0ec356',
    messagingSenderId: '981749862755',
    projectId: 'skilloom',
    storageBucket: 'skilloom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPyEMAYFOKTPHYMOm1exr8afJj3NZu_tU',
    appId: '1:981749862755:ios:15cc4835b95b3c8e0ec356',
    messagingSenderId: '981749862755',
    projectId: 'skilloom',
    storageBucket: 'skilloom.appspot.com',
    iosClientId: '981749862755-dfcpg9roj1jtp1o82ul972amfiaq79hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cogniversity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPyEMAYFOKTPHYMOm1exr8afJj3NZu_tU',
    appId: '1:981749862755:ios:15cc4835b95b3c8e0ec356',
    messagingSenderId: '981749862755',
    projectId: 'skilloom',
    storageBucket: 'skilloom.appspot.com',
    iosClientId: '981749862755-dfcpg9roj1jtp1o82ul972amfiaq79hc.apps.googleusercontent.com',
    iosBundleId: 'com.example.cogniversity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQ_8IEKMv0yHALdWw6k8I5eyamyr5JfEY',
    appId: '1:981749862755:web:3596968a4ee5fa590ec356',
    messagingSenderId: '981749862755',
    projectId: 'skilloom',
    authDomain: 'skilloom.firebaseapp.com',
    storageBucket: 'skilloom.appspot.com',
    measurementId: 'G-MXHQMYHNG0',
  );
}
